### ISSUE TITLE
Internal Exception: io.netty.handler ...

### ISSUE THREAD

**Issue by Oalecj** [shoghicp/BigBrother#40] opened 2015-02-24 23:51 UTC
Internal Exception: io.netty.handler.codec.DecoderException: java.io.EOFException: feildSize is too long! Length is 65407, but maximum is 0.

How to reproduce bug: Join server with latest BigBrother, (log in if you have SimpleAuth), if you logged in with the same username you do with PE, you will be frozen. Do /kill (your name). Receive error. Reconnect. Receive error.

I currently cannot get the log from the server console, but when I do:
(future link if I can edit, can't remember)
Also screenshot from the game:
![errorbb](https://cloud.githubusercontent.com/assets/8262255/6361983/dd81cab0-bc3c-11e4-88b4-57b749208887.PNG)

If you log in from your iOS/Android device and respawn, the error STILL happens.

**Comment by alejzeis** [comment] 2015-03-26 14:20
Duplicate of #38

**Closed as completed** 2015-03-26 14:50 UTC
